version: '3.0'

services:
  producer:
    build: ./
    container_name: kafka_producer_1
    restart: on-failure
    volumes:
      - ../streaming_data:/usr/src/app/datasets/
    networks:
      - myNetwork

networks:
  myNetwork:
    external: true