version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - '2181:2181'
  
  kafka:
    image: 'bitnami/kafka:3'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    restart: on-failure
    depends_on:
      - zookeeper

  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    volumes:
      - ./producer.py:/producer.py
    container_name: producer
    restart: on-failure
    depends_on:
      - kafka
  
  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    volumes:
      - ./consumer.py:/consumer.py
    container_name: consumer
    restart: on-failure
    depends_on:
      - kafka